db:
  image: mysql:5.7
  environment:
    MYSQL_USER: docker
    MYSQL_ROOT_PASSWORD: dummy
    MYSQL_PASSWORD: dummy
    MYSQL_DATABASE: dummy
  ports:
    - 8889:3306

# Here's where you step in...
# Define one of these for each WordPress installation you develop. Remember to
# define the host (WP_LOCAL_DOMAIN) in /etc/hosts, i.e., map 127.0.0.1 (Linux)
# or the IP address of the docker-machine (Win, Mac OSX) to your development
# domains so that you can access the sites from your browser. If you're on Mac
# OSX, give Gas Mask (https://github.com/2ndalpha/gasmask) a try.
mytheme:
  extends: 
    file: ./docker/docker-compose.yml
    service: wordpress
  links:
    - db:mysql
  environment:
    WP_LOCAL_DOMAIN: mytheme.dev
    WP_ASSETS_DOMAIN: some.domain.com

