#!/bin/bash

pushd $(dirname ${BASH_SOURCE[0]}) &> /dev/null

if ! which docker-compose || ! which docker-machine; then
  echo "You do not have Docker in your \$PATH. Please, check your Docker Toolbox installation" >&2
  exit 1
fi

touch ../debug.log
chmod a+w ../debug.log

if [[ $(docker-machine status default) != "Running" ]]; then
  echo "Starting the Docker machine"
  docker-machine start
fi

echo "Starting the Docker build. It may take several minutes... [y/n]"
eval "$(docker-machine env default)"
docker-compose build

exit 0
